### ISSUE TITLE
Grid search variant

### ISSUE THREAD

**Issue by SimonBlanke** [SimonBlanke/Gradient-Free-Optimizers#10]
I think it would be useful to have a grid search optimizer in this package. But its implementation would probably be quite different from other ones (sklearn, ...). 

The requirements are:
 - The grid search has to stop after n_iter instead of searching the entire search space
 - The positions should not be precalculated at the beginning of the optimization (i have concerns about memory load).

**Comment by djokester** [comment]
@SimonBlanke let me start with this.

**Comment by SimonBlanke** [comment]
@djokester I would like to give you some guidance for this task:

You can start by creating the class "GridSearch" and inherit both the [BaseOptimizer](https://github.com/SimonBlanke/Gradient-Free-Optimizers/blob/master/gradient_free_optimizers/optimizers/base_optimizer.py) and [Search](https://github.com/SimonBlanke/Gradient-Free-Optimizers/blob/master/gradient_free_optimizers/search.py). You can use [random search](https://github.com/SimonBlanke/Gradient-Free-Optimizers/blob/master/gradient_free_optimizers/optimizers/random/random_search.py) as a template for this.

You should also keep in mind that each optimizer has the following methods:
 - init_pos (initializes the positions given in "initialize". In most cases this can just be inherited from BaseOptimizer)
 - finish_initialization (most optimizers don't use this. Just inherit this from BaseOptimizer)
 - iterate (very important! This returns the next position)
 - evaluate (what to do after the score is calculated for the new position. E.g. move to the new position if better than current.)

For the GridSearch init_pos, finish_initialization and evaluate can be inherited from BaseOptimizer. "evaluate" doesn't need to be implemented for GridSearch because it does not decide what to do next based in the new score.

This is all I figured out about the implementation. I hope this helps!

**Comment by djokester** [comment]
Yeah @SimonBlanke. 
Thanks it helps a lot

**Comment by SimonBlanke** [comment]
Hello @djokester,

have you made some progress on the grid search algorithm? If you need some additional assistance I would be happy to help.

**Comment by djokester** [comment]
@SimonBlanke I have gone through the code base. I will send a PR by this weekend.

**Comment by SimonBlanke** [comment]
@djokester a PR would be nice! You can ignore the extended tests (performance, parameters, ...), I will take care of those. If you have a basic concept we can continue from that together.

**Comment by cryptocoinserver** [comment]
@djokester Any news? Thank you for your time!

**Comment by tgdn** [comment]
@cryptocoinserver we have an open PR #18, let us know what you think!

**Comment by SimonBlanke** [comment]
@tgdn and his team @EdouardVilain-Git, @tabeare, @annabieber, @MachineLearner75 provided an implementation of grid-search, which can be used in Gradient-Free-Optimizers >= v0.5.0. 

You can read more about it in the [optimization-tutorial](https://github.com/SimonBlanke/optimization-tutorial).
