### ISSUE TITLE
API for v1.0.0 of Gradient-Free-Optimizers

### ISSUE THREAD

**Issue by SimonBlanke** [SimonBlanke/Gradient-Free-Optimizers#2]
In this issue the progress for the final api-design for Gradient-Free-Optimizers is tracked.

**Comment by SimonBlanke** [comment]
The current idea is to merge the two arguments "memory" and "memory_warm_start" into one argument "memory".

 - memory is True or False.
 - memory_warm_start is None or a dataframe containing the search-data that gets passed into the memory dictionary

It would not make much sense to set "memory" to False, while passing search-data to  "memory_warm_start". The search-data would not get used.

In the future you can pass the search-data to memory and the memory within GFO is automatically set to True.

**Comment by SimonBlanke** [comment]
The attribute containing the results of the search should be renamed from "results" to "search_data".

**Comment by SimonBlanke** [comment]
The parameter "warm_start_smbo" of the sequence model based optimizers will accept another data type.
Instead of a tuple of arrays the user can just pass the "search_data" dataframe.

**Comment by SimonBlanke** [comment]
The "random_state" parameter should be moved from the search-method to the optimizer-class as discussed in SimonBlanke/Gradient-Free-Optimizers#7.

**Comment by d416** [comment]
> The attribute containing the results of the search should be renamed from "results" to "search_data".

Hi Simon, it appears that "results" is still the go-to method whereas "search_data" returns an error.

I'm using the EvolutionStrategyOptimizer in version 1.04 from pypi (Python 3.9). 

`AttributeError: 'EvolutionStrategyOptimizer' object has no attribute 'search_data'`

 Came here for a clue as to what could have gone wrong and saw this commit.  This library is a great thoughtful piece of work Thank you for sharing it
