### ISSUE TITLE
only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by k-aliyah** [SimonBlanke/Gradient-Free-Optimizers#20]
**Describe the bug**
every time going to the 11th iteration there is a bug 
**Code to reproduce the behavior**
import numpy as np
from gradient_free_optimizers import EvolutionStrategyOptimizer,ForestOptimizer,OneDimensionalBayesianOptimization
from gradient_free_optimizers import BayesianOptimizer,TreeStructuredParzenEstimators

opt =TreeStructuredParzenEstimators(search_space)
tes=opt.search(minimizeobjective,n_iter=1000)

**Error message from command line**

  File "/home/kinanti_a/anaconda3/envs/spyder/lib/python3.8/site-packages/gradient_free_optimizers/optimizers/smb_opt/tree_structured_parzen_estimators.py", line 53, in <listcomp>
    best_samples = [self.X_sample[i] for i in index_best]

TypeError: only integer scalar arrays can be converted to a scalar index
**System information:**
 - OS Platform and Distribution Linux
 - Python version 
 - Gradient-Free-Optimizers version 1.0.1

**Additional context**

**Comment by SimonBlanke** [comment]
Hello @k-aliyah,

thank you for reporting this bug! :-) 
I was not able to reproduce this error. I need the complete code to reproduce this behavior. In your code there is no search space and no objective function.

Also: The `OneDimensionalBayesianOptimization` is an experimental-optimizer, that is not yet officially supported.

**Comment by k-aliyah** [comment]
> Hello @k-aliyah,
> 
> thank you for reporting this bug! :-) I was not able to reproduce this error. I need the complete code to reproduce this behavior. In your code there is no search space and no objective function.
> 
> Also: The `OneDimensionalBayesianOptimization` is an experimental-optimizer, that is not yet officially supported.

thank you very much for your prompt response! I realized it was indeed my objective function that is not compatible with bayesian and TPE, but it was working with ES.
