### ISSUE TITLE
AttributeError: "Optimizer" object has no attribute 'search_data'

### ISSUE THREAD

**Issue by SimonBlanke** [SimonBlanke/Gradient-Free-Optimizers#22]
> The attribute containing the results of the search should be renamed from "results" to "search_data".

Hi Simon, it appears that "results" is still the go-to method whereas "search_data" returns an error.

I'm using the EvolutionStrategyOptimizer in version 1.04 from pypi (Python 3.9). 

`AttributeError: 'EvolutionStrategyOptimizer' object has no attribute 'search_data'`

 Came here for a clue as to what could have gone wrong and saw this commit.  This library is a great thoughtful piece of work Thank you for sharing it

_Originally posted by @d416 in https://github.com/SimonBlanke/Gradient-Free-Optimizers/issues/2#issuecomment-1008435040_

**Comment by SimonBlanke** [comment]
Hello @tgdn,

thank you very much for your comment :-) 
I opened a separate issue for this, because it sounds like a bug.

Could you give an example script, that I can copy and run to reproduce this error?

**Comment by d416** [comment]
@SimonBlanke Unable to reproduce - environments must have been mixed up when I wrote the comment.  I think we can close this. Thanks

**Comment by SimonBlanke** [comment]
@d416

no problem, I'll close it.
