### ISSUE TITLE
RuntimeWarning about np.exp() overflow 

### ISSUE THREAD

**Issue by Wollala** [SimonBlanke/Gradient-Free-Optimizers#24]
Error msg as below
```bash
gradient_free_optimizers/optimizers/local_opt/simulated_annealing.py:22: RuntimeWarning: overflow encountered in exp
  return np.exp(-self._score_norm_default() / self.temp)
```

**Comment by SimonBlanke** [comment]
Hello @Wollala,

this is not an error but only a warning that numpy cannot handle the size of the exp-function. The result is `inf`, which does not break the behaviour of the simulated annealing optimizer. The occurrence of this warning is expected during normal operation. If the warnings clutter your command-line you can silence them separately.
