### ISSUE TITLE
Errors when there is only one option for a hyperparameter

### ISSUE THREAD

**Issue by SimonBlanke** [SimonBlanke/Gradient-Free-Optimizers#5]
I opened this issue because @mattwedge encountered a problem in SimonBlanke/Hyperactive#16. The sequence model based optimizers cannot handle if a dimension of the search space has a size of 1.

I think this is a feature that is important for all optimizers. It adds to the flexibility of the exploration of the objective function.

The error occurs because in smb-optimizers a list of the combinations of all positions in the search space is calculated. But when a dimension has a size of 1 it returns an empty array. I will look into this problem and figure out why this happens.

**Comment by SimonBlanke** [comment]
I fixed the error in 81de005a08fd271eb22f75dd9cc38991bba7b04b. The fix is available in version 0.2.14 that i just uploaded.
It passed all current tests in Gradient-Free-Optimizers and Hyperactive. So it can be used by just updating Gradient-Free-Optimizers.

I also added tests for this case in commit f054f71836524ff4c6ec56910958d4c043a7f71e.

@mattwedge let me know if this solution works for you.

**Comment by mattwedge** [comment]
> I fixed the error in [81de005](https://github.com/SimonBlanke/Gradient-Free-Optimizers/commit/81de005a08fd271eb22f75dd9cc38991bba7b04b). The fix is available in version 0.2.14 that i just uploaded.
> It passed all current tests in Gradient-Free-Optimizers and Hyperactive. So it can be used by just updating Gradient-Free-Optimizers.
> 
> I also added tests for this case in commit f054f71836524ff4c6ec56910958d4c043a7f71e.
> 
> @mattwedge let me know if this solution works for you.

Amazing, thanks a lot for the fast work! Will try this out ASAP

**Comment by mattwedge** [comment]
> > I fixed the error in [81de005](https://github.com/SimonBlanke/Gradient-Free-Optimizers/commit/81de005a08fd271eb22f75dd9cc38991bba7b04b). The fix is available in version 0.2.14 that i just uploaded.
> > It passed all current tests in Gradient-Free-Optimizers and Hyperactive. So it can be used by just updating Gradient-Free-Optimizers.
> > I also added tests for this case in commit [f054f71](https://github.com/SimonBlanke/Gradient-Free-Optimizers/commit/f054f71836524ff4c6ec56910958d4c043a7f71e).
> > @mattwedge let me know if this solution works for you.
> 
> Amazing, thanks a lot for the fast work! Will try this out ASAP

Works perfectly :)

**Comment by SimonBlanke** [comment]
Very good! Thank you again for pointing out this issue. Just let me know if another problem appears.
