### ISSUE TITLE
DIRECT optimizer

### ISSUE THREAD

**Issue by SimonBlanke** [SimonBlanke/Gradient-Free-Optimizers#8]
Multiple users requested DIRECT optimizer in this package. This issue will track the process of its implementation and improvement.

**Comment by djokester** [comment]
Hey @SimonBlanke!
Do you mind if I work on this?
if you have started working on this maybe you can give me something else to work on?

**Comment by SimonBlanke** [comment]
Hello @djokester,

you are very welcome to work on this (or another) issue. I have not started working on this algorithm yet. But there are some things you should keep in mind:

Implementing new optimization algorithms is usually quite difficult for other developers because there are some strict requirements to make them work in the same API. Because of this all optimizers have something like a "backend API". All optimizers have the following methods:
 - init_pos()
 - iterate()
 - evaluate()
 - finish_initialization()

Those are then used in [search.py](https://github.com/SimonBlanke/Gradient-Free-Optimizers/blob/master/gradient_free_optimizers/search.py). 
Also: The code is currently not well documented and explained.

If you want another task that would be a better introduction to this package I opened multiple new issues.

**Comment by SimonBlanke** [comment]
Hello @djokester,

I was able to implement the direct search, based on the explanation [in this fantastic article](https://link.springer.com/article/10.1007/s10898-020-00952-6#:~:text=Introduced%20in%201993%2C%20the%20DIRECT,hyperparameter%20(the%20desired%20accuracy).). It was much easier to understand this algorithm after I understood and implemented the [Lipschitz Optimizer](https://github.com/SimonBlanke/Gradient-Free-Optimizers/issues/27), but it was quite the challenge!

It will be released in v1.2 and can already be seen in the [corresponding branch](https://github.com/SimonBlanke/Gradient-Free-Optimizers/blob/v1.2/gradient_free_optimizers/optimizers/global_opt/direct_algorithm.py). If you like you can take a look at the source-code and give suggestions.

This is the search-path in a convex optimization-problem:

![DirectAlgorithm](https://user-images.githubusercontent.com/20640612/182020344-ddf49ef3-e8b0-4e9c-9a6f-8521de6f6236.gif)

**Comment by SimonBlanke** [comment]
this feature was released in v1.2
